# Generated by Django 4.1.1 on 2022-10-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='feedback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='feedback',
            field=models.FloatField(default=0.0),
        ),
    ]
